### ISSUE TITLE
是否有必要将 KBUILD_BUILD_USER 转为小写？

### ISSUE THREAD

**Issue by ad3wc659b4e4f** [WenHao2130/android_kernel_oppo_sdm660#8]
我在查阅资料后并未发现文档中有对 `KBUILD_BUILD_USER` 大小写的确切说明，并且有不少的内核的 `KBUILD_BUILD_USER` 确实为大小写混合。部分情况下，保持 `KBUILD_BUILD_USER` 中的大写字符有助于提高 `uname` 信息的可读性。故：是否可以从构建配置中设置 `KBUILD_BUILD_USER` 的语句（如下）https://github.com/WenHao2130/android_kernel_oppo_sdm660/blob/200ea8cae68822665493668f53f57dcf9dd77e78/.github/workflows/Kbuild_all.yml#L40 中删去处理大小写的 ` | tr A-Z a-z`？

---

另：此议题显然不适合放于 Issues 中讨论，故是否能打开 Discussion？

**Comment by WenHao2130** [comment]
个人认为`uname`中并未出现其他大写字符，~~将用户名处理为小写会比较符合规则~~
另外，已开放Discussion

**Comment by WenHao2130** [comment]
您如果需要大写的用户名可以Fork后自行修改呢~
